feat: Update naas.secret with new method
jupyter-naas/naas pull request #438
Opened 2024-02-06 13:28 UTC by l-loic

this issue resolve #437

2024-02-23 17:08 UTC, Dr0p42 requested changes
Thank you @l-loic for the pull request. I opened an issue that should be done before proceeding, it will improve the experience, because I am concerned that people might stop the kernel or restart it while the `naas.list` is actually porting everything if they have a lot of secrets.

2024-02-23 17:08 UTC, Dr0p42 commented on naas/secret.py
> +            print("Secret get failed")
We need to have a better error handling here to make sure it reflects the issue we are getting and to help the user fix the issue.

2024-02-23 17:08 UTC, Dr0p42 commented on naas/secret.py
> +        remote_secret = self.__get_remote_secret(name=name)
I commented the try/except because it was messing with the SecretNotFound error. But we still need to display something if we have a connection error to api.naas.ai I think

2024-02-23 17:08 UTC, Dr0p42 commented on naas/secret.py
> +            self.__create_remote_secret(name=row['name'], value=row['secret'])
This one is doing all of them one by one, which was slow on my account (30+ secrets), I opened this issue to mitigate that: https://github.com/jupyter-naas/naas-api-ce/issues/77 

It should be done before merging this pull request

2024-03-18 07:56 UTC, FlorentLvr commented
@Dr0p42, @l-loic, could you please merge this PR if it's good?

2024-03-18 09:33 UTC, Dr0p42 requested changes
Hello @l-loic, I bumped to the latest version of nasa-python, and the bulk create seems to work ok.

There is a last error though when trying to get a non existing secret:

<img width="777" alt="image" src="https://github.com/jupyter-naas/naas/assets/22365519/665d0a30-8f84-4d6e-91c5-abceaf93f3a5">

This is what is expected:

<img width="436" alt="image" src="https://github.com/jupyter-naas/naas/assets/22365519/86184681-ee21-4930-b9cf-6a49328c6240">

2024-03-18 14:05 UTC, merged